### ISSUE TITLE
sync before suspend

### ISSUE THREAD

**Issue by mattia-b89** [graysky2/profile-sync-daemon#231]
Several times I lost last part of my work on browser (open tabs, bookmarks, history, ...).
This happens when my laptop fails to resume (a known hardware fault).

Talking about `psd`, is there a way to workaround it? Forcing the `psd` service to sync profile when pc calls for a suspend? Or actually is this already done?

**Comment by graysky2** [comment]
I believe there is a way using the `suspend.target` ... let me look into it.

**Comment by graysky2** [comment]
@mattia-b89 - I am not expert with this, can you please try using the following as your `/usr/lib/systemd/user/psd-resync.service` and report back.

1. `systemctl --user stop psd`
2. edit the file replacing it the the following contents
3. `systemctl --user daemon-reload`
4. `systemctl --user start psd`

```
[Unit]
Description=Timed resync
After=psd.service
Before=sleep.target
Wants=psd-resync.timer
PartOf=psd.service

[Service]
Type=oneshot
ExecStart=/usr/bin/profile-sync-daemon resync

[Install]
WantedBy=default.target suspend.target
```

**Comment by mattia-b89** [comment]
sure, I've already done it!
Now, I am trying to *test* the change but this is the *hard* part, now...
In fact currently I do not have no more problems with suspend/resume and I am working on a laptop without the ability to extract the battery, thus I do not have idea on how to simulate a broken suspend/resume;  
Any ideas?

**Comment by graysky2** [comment]
First step is to confirm that the changes above give the expected behavior, eg that psd does the re-sync when you suspend the laptop.  You should see this reflected in the journal.

This will show progress towards the hourly resync: `systemctl --user list-timers`
So long as the timer triggered it, this will show you everything `psd-resync` did: `journalctl --user -u psd`

Please suspend the laptop taking note of the time you did it. Did you see a corresponding entry in the journal?

**Comment by mattia-b89** [comment]
Unfortunately the change does not work as intended: I get no resync when I suspend the laptop.

**Comment by graysky2** [comment]
I will have to read a bit more on this.

**Comment by mattia-b89** [comment]
I am here to help you/test. Let me know

**Comment by graysky2** [comment]
OK... I think this should work:

1. `systemctl --user stop psd`
2.  Edit `/usr/lib/systemd/user/psd-resync.service` replacing it the the contents below
3. `systemctl --user daemon-reload`
4. `systemctl --user start psd`

```
[Unit]
Description=Timed resync
After=psd.service
Before=sleep.target
Wants=psd-resync.timer
PartOf=psd.service

[Service]
Type=oneshot
ExecStart=/usr/bin/profile-sync-daemon resync

[Install]
WantedBy=default.target
WantedBy=sleep.target
```

**Comment by mattia-b89** [comment]
nope, same output as above

**Comment by graysky2** [comment]
@mattia-b89 - Please see [this](https://bbs.archlinux.org/viewtopic.php?id=254728) discussion.  Enabling this is surprisingly complex.  Seems the most straightforward route is with a [sleep hook](https://wiki.archlinux.org/index.php/Power_management#Sleep_hooks)... but that requires the user to hard code his/her username into the service.

**Comment by mattia-b89** [comment]
First, thank you for your effort!
Right now, I think you have (already) done the most important thing: open a **systemd issue upstream**
and honestly, it is hard to believe it lacks of a such feature.

---

Second, my personal thought is:  
I am the first who think code must be as simple as possible. Keep it as elegant as today. No workaround, no complex code. Do not waste time for a trick that will never works 100%
So, let's go beyond this feature but let's keep this issue open, as a *place holder*.

**Comment by graysky2** [comment]
I created a more detailed, formal feature request: https://github.com/systemd/systemd/issues/15477

**Comment by glitsj16** [comment]
I took a stab at implementing this as cleanly as possible in #261. Please feel free to review and make suggestions. I did some extended testing on both Arch Linux and Ubuntu LTS (16.04 and 20.04) with these patches and for me it works. I do realize @graysky2 stated not wanting to integrate something _messy_, which I fully understand. So it's up to the owner to proceed on this as he sees fit.

**Comment by graysky2** [comment]
@glitsj16 - This is looks like a really nice solution.  If merged, I might add a setting with `psd.conf` to enable it so others who do not suspend can maintain a minimal footprint (although your helper script is tiny).

@mattia-b89 - Can you kick the tires on this on your system?  I never suspend my workstation.

**Comment by glitsj16** [comment]
> [...] I might add a setting with psd.conf to enable it so others who do not suspend can maintain a minimal footprint [...]

@graysky2 Didn't think of that. Easily turned into an `optional` feature though. In fact, a default of "no" makes more sense. Not only will it take the user's explicit consent, it might make them aware of the added - now optional - dependency on gdbus/glib2. Will adjust the PR accordingly.

**Comment by glitsj16** [comment]
Here's a short overview of the needed steps to have psd resyncing on suspend:

```
- check if you have `gdbus` installed (comes with the _glib2_ package)
- stop psd service
- set `USE_SUSPSYNC="yes"` in ~/.config/psd/psd.conf
- start psd.service
- `psd p` will show the current sync on sleep protection status
```

Invoke suspend (preferrably several times during the same desktop session):
```
- via your favo DE
- via CLI
    - $ systemctl suspend
    - $ gdbus call --system --dest org.freedesktop.login1 --object-path /org/freedesktop/login1 --method org.freedesktop.login1.Manager.Suspend true);
- via [GUI](https://wiki.archlinux.org/index.php/D-Bus#Debugging) tools
```

Confirm it's working by grep'ing/tailing your journal:
```
- $ journalctl | grep "psd-suspend-sync"
- $ journalctl --no-hostname -f
```

**Comment by graysky2** [comment]
@glitsj16 - This looks nice!  The only thing I would add is that the inhibition lock can be verified via:
`systemd-inhibit --list`

We still need some folks to test this out before rolling out into a stable release.  I merged into my sync-on-sleep branch and tagged it as [v6.39b1](https://github.com/graysky2/profile-sync-daemon/releases/tag/v6.39b1)

@mattia-b89 - Would you please build and use [v6.39b1](https://github.com/graysky2/profile-sync-daemon/releases/tag/v6.39b1) and let us know?

**Comment by graysky2** [comment]
@glitsj16 - Note that you can also see the inhibition lock via:
`systemd-inhibit --list`

I merged, edited a little and rebased into my sync-on-sleep branch and tagged it as [v6.39b2](https://github.com/graysky2/profile-sync-daemon/releases/tag/v6.39b2)

Why does `/usr/bin/psd-suspend-sync` appear twice in a ps output?

```
% ps aux | grep psd-sus
facade  3694933  0.0  0.0  17068  6528 ?        S    06:09   0:00 systemd-inhibit --mode=delay --what=sleep --who=profile-sync-daemon --why=psd resync on suspend /usr/bin/psd-suspend-sync
facade  3694942  0.0  0.0   7140  2960 ?        S    06:09   0:00 /bin/bash /usr/bin/psd-suspend-sync
facade  3694945  0.0  0.0   7140   420 ?        S    06:09   0:00 /bin/bash /usr/bin/psd-suspend-sync
```

@mattia-b89 - Would you please build and use [v6.39b2](https://github.com/graysky2/profile-sync-daemon/releases/tag/v6.39b2) and let us know?

**Comment by mattia-b89** [comment]
@graysky2 sure, during the weekend I will give it a try

**Comment by mattia-b89** [comment]
errata, I have just installed version **6.39b2**

```
$ journalctl | grep "psd-suspend-sync"
Apr 29 18:43:53 arch-xps mattia[11041]: [psd-suspend-sync] Issueing suspend-sync request...
Apr 29 18:44:00 arch-xps mattia[11387]: [psd-suspend-sync] re-taking inhibit lock...
```

also `$ ps aux | grep psd-sus` returns 2 entries
what else can I check?

**Comment by glitsj16** [comment]
> Why does /usr/bin/psd-suspend-sync appear twice in a ps output?
> also $ ps aux | grep psd-sus returns 2 entries

@graysky2 @mattia-b89 My guess is that this is a side-effect of grep'ing ps output, it includes the `psd-sus` from the piped grep. IMO it's more accurate to use pgrep. For example, even when psd is stopped, which also kills psd-suspend-sync, grep'ing ps output will still show what is being grep'ed for:

```
$ systemctl --user stop psd
$ ps aux | grep -c psd-sus
1
$ pgrep -cf "/usr/bin/psd-suspend-sync"
0
```

That being said, there **are** in fact always 2 psd-suspend-sync processes running if the user enabled the option. This is caused by the fact I used a _direct_ call to `systemd-inhibit` in the take_inhibit_lock() function in profile-sync-daemon. Give me some time to experiment if using the [logind D-Dbus API](http://www.freedesktop.org/wiki/Software/systemd/logind) instead can bring it down to only the one psd-suspend-sync process running. I can see how that might cause confusion. Functionality-wise there isn't a difference, psd **is** doing the resync on suspend just fine. Thanks for pointing this out here!

**Comment by glitsj16** [comment]
@graysky2 shellcheck reported one issue with the profile-sync-daemon from your sync-on-sleep branch:
```
$ /usr/bin/shellcheck -s bash /usr/bin/profile-sync-daemon

In /usr/bin/profile-sync-daemon line 119:
    IFS=' ' read -r -a BROWSERS <<< "$BROWSERS"
                                                               ^-------^ SC2128: Expanding an array without an index only gives the first element.

For more information:
  https://www.shellcheck.net/wiki/SC2128 -- Expanding an array without an ind...
```

If you want I can open a seperate issue for it, but I guess you can fix it easily by using ... <<< "${BROWSERS[$@]}" correct?

**Comment by graysky2** [comment]
> If you want I can open a seperate issue for it, but I guess you can fix it easily by using ... <<< "${BROWSERS[$@]}" correct?

I will change it... (actually I did commit this before).  Thanks!

Regarding the `--who=`... let's just leave it as-is since UID and USER are already captured.  Let me know what you want to do about logind D-Dbus API but I think it's fine so long as seeing 2 is to be expected.

**Comment by glitsj16** [comment]
> Regarding the --who=... let's just leave it as-is since UID and USER are already captured.

True, that should do it.

> Let me know what you want to do about logind D-Dbus API but I think it's fine so long as seeing 2 is to be expected.

I did another round of experimenting on this yesterday and - as we type - I'm trying to get basic confirmation on irc.freenode.org/systemd that this is indeed 'normal' behavior (if there is such a thing in D-Bus land). After several days of quite extensive testing I do feel we have a reliable resync-on-suspend framework now. I'll keep you informed here if something relevant pops up from the IRC channel visit. Take care!

**Comment by graysky2** [comment]
Sounds good @glitsj16.  Thank you for the contributions and for the diligence!

>@graysky2 sure, during the weekend I will give it a try

@mattia-b89 - Great, please do.

**Comment by graysky2** [comment]
> sure, during the weekend I will give it a try

@mattia-b89 - Any feedback?

**Comment by mattia-b89** [comment]
I have been testing it for a week and I encountered no issue

**Comment by graysky2** [comment]
> I have been testing it for a week and I encountered no issue
Glad to hear it, I too have been using it and seeing it work as expected.

**Comment by glitsj16** [comment]
Great to hear the testing has gone OK. All the best in these bizarrely trying pandemic times.

**Comment by graysky2** [comment]
You too!
